src/components/Banner.tsx
src/css.ts

Would it be possible that you could review the changes that I have added to the Banner.tsx and css.ts

table layout and styles adjusted on the Banner component

---

package.json
src/components/Banner.tsx
src/components/Card.tsx
src/components/Footer.tsx
src/components/Heading.tsx
src/components/Multiline.tsx
src/css.ts
src/email.tsx
src/layout/Center.tsx
src/layout/Padding.tsx
src/styles/card-padding.ts
tslint.json

The aim here is to help ensure we don't use styles in a way that will break email clients, which are quite particular about things.
I think this will cause some conflicts (which I'll fix when they arise) but would be great to get thoughts @Krystian-gnm on the type stuff here.

Narrow types for styling

---

tslint.json

Set arrow-parens to false

---

.githooks/pre-push/validate
package.json
yarn.lock

I'd originally added emotion as thought we'd use it, but switched to simple React as couldn't see a way to use emotion with inline styles, which is what email HTML requires.

No emotion

---

.vscode/extensions.json
src/api.ts
src/email.tsx
src/image.test.ts
src/image.ts

Adds star rating overlay when a rating is present.
https://trello.com/c/dznEXTrv

Star ratings

---

src/api.ts
src/components/Collection.tsx
src/email.tsx

To help readability and in anticipation of the collection component becoming more complex as we support types beyond just film.

Move collection into separate component

---

.githooks/pre-push/validate
src/components/Card.tsx
src/css.ts

Fixes a few of the type errors - although a couple remaining that we'll fix separately!
Also, prevents pushing a commit if there are type errors or lint errors (previously it would only warn). You can always ignore these using the `--no-verify` flag for git push but this is discouraged.

Fix some type errors

---

src/email.tsx

Just going to merge this as it is required to do braze visual testing.

Close html tag

---

README.md

Readme file updated with useful links for code snippets and bug fixes + section with 'Special fixes' added in.

Readme file updated 

---

.gitignore
bin/upload.sh
src/Text.tsx
src/server.ts

This is a basic script to upload to S3 for Braze to access for the inital a/b test. We'll have to run it manually for now.

Add tmp script to write responses to s3 for inital a/b test

---

src/Text.tsx
src/api.ts
src/server.ts

We hard-coded the text headline for the test but let's make it dynamic!

Fix text headline

---

src/Email.tsx
src/components/Card.tsx
src/components/Multiline.tsx
src/css.ts
src/layout/Center.tsx

Keeping byline on separate line across mobile and desktop view.

Keeping byline on separate line across mobile and desktop view.

---

src/Email.tsx
src/api.ts
src/components/Collection.tsx
src/components/cards/Card.tsx
src/components/cards/CommentCard.tsx
src/components/cards/DefaultCard.tsx
src/layout/Grid.tsx

Introduce branching on card component by card display type. At the moment the 'CommentCard' is exactly the same as the default one but that will change!

Support multiple card display types

---

package.json
src/api.ts
src/components/cards/Card.tsx
src/components/cards/CommentCard.tsx
src/css.ts
src/layout/ColumnPadding.tsx
src/layout/RowCellPadding.tsx
src/layout/Table.tsx
yarn.lock

A combination of some great design work by Krystian and then some joint refactoring to try and improve how we handle tables now that they are everywhere! 😱

Comment card styling (initial work)

---

src/api.ts
src/components/Collection.tsx
src/components/cards/CommentCard.tsx
src/css.ts
src/layout/Grid.tsx
src/layout/Padding.tsx

Our work on getting the comment collection visually done.

Comment card

---

src/components/cards/CommentCard.tsx
src/components/cards/DefaultCard.tsx

For some reason extending of the headlineStyle on the kickerStyle didn't work, so I have decided to create a new arrow function and pass the styles in here. (It would be great if we could have a chat why this didn't work).

Fixing the issue with the kicker styling on DeafaultCard and CommentCard

---

bin/upload.sh
src/Email.tsx
src/components/Banner.tsx
src/components/Collection.tsx
src/components/Collections.tsx
src/components/cards/CommentCard.tsx
src/components/cards/MediaCard.tsx
src/layout/Table.tsx

As we need more than one! Also some other additions - see individual commits - as we got carried away.

Support multiple collections and more

---

src/components/cards/CommentCard.tsx
src/layout/Grid.tsx

Some clients don't like the current approach/require display:block!

(Attempt) Fix image styling on certain clients

---

src/api.ts
src/components/Collection.tsx
src/components/Collections.tsx
src/components/cards/Card.tsx
src/components/cards/CommentCard.tsx
src/components/cards/LinkCard.tsx
src/layout/Grid.tsx

A first draft of the link snaps collection type:

Add basic styling for link snaps

---

src/Email.tsx
src/components/Footer.tsx

Small fix to make link dynamic.

Make trouble viewing link dynamic

---

src/components/Collection.tsx
src/components/Collections.tsx
src/components/Footer.tsx
src/components/Multiline.tsx
src/components/tests/commentB/Collection.tsx
src/components/tests/commentB/Grid.tsx
src/components/tests/commentB/LinkCard.tsx
src/components/tests/commentB/MediaCard.tsx
src/components/tests/commentC/Collection.tsx
src/components/tests/commentC/Grid.tsx
src/components/tests/commentC/LinkCard.tsx
src/components/tests/commentC/MediaCard.tsx
src/layout/Grid.tsx

Implements styling for the remaining card differences!

Style media and link cards for C variant

---

.github/PULL_REQUEST_TEMPLATE.md

Adds the same PR template we use in DCR.
Because it's good to give more context to the PRs by describing what they do and what the motivation was. Also, it will encourage us to card up all non trivial changes.
https://trello.com/c/MVpWAmcz/68-add-pr-template

Adding same PR template from DCR

---

src/cdk/app.ts

Fix it.
Because it is broken.
n/a

Fix healthcheck type

---

README.md

Note on project status. (We need to confirm if this is the case before merging though or whether we'll complete the migration first.)
To not confuse people!
n/a

Document status

---

docs/04-testing-emails.md

Closes #106 by moving the Braze notes to the testing docs.

Add Braze testing notes

---

README.md
docs/01-getting-started.md
docs/02-email-limitations.md
src/api.ts
src/image.ts

After moving from using `master` to `main` for the main branch, we need
to update all existing references in the codebase.
Closes #119

Update references to master branch
