.githooks/pre-push/validate
package.json
yarn.lock

Just to help with formatting etc and not committing errors.
Can be ignored with `--no-verify` if required.

Pre-push hook

---

package.json
src/email.tsx
src/image.test.ts
src/image.ts
src/server.ts
src/styles/typography.test.ts
yarn.lock

*Note, at the moment this will error on startup if you haven't set an IMAGE_SALT env var. It feels like we should load this from config instead based on credentials to improve dev ex but that will be later/separate PR.*
Use CDN for caching, format and sign images.
See https://docs.fastly.com/api/imageopto/ for Fastly image formatting options.
The signing process is essentially md5 of the path+query string with an added salt.

Sign and format images

---

src/components/Footer.tsx

Setting a background color as an attribute bgcolor on table fixes the issue with missing background-color on Lotus Notes 8.5

Background color fix for footer section in Lotus Notes 8.5

---

src/components/Collection.tsx
src/components/Footer.tsx
src/email.tsx

Please note that currently link to a "Trouble viewing?" in the footer is linking to a current live preview of the email and this will have to be updated to a new endpoint before we send the Live test.

Braze parameter added in and footer links updated

---

src/layout/Center.tsx

Deprecated center tag has been removed and replaced with a table > tr > and td aligned center.

Deprecated center tag removed.

---

src/api.ts
src/components/Card.tsx
src/components/Collection.tsx
src/css.ts
src/kicker.ts

Only supports free html initially (and not even html), but we'll expand as we go.
But really, this kind of thing should live upstream to avoid duplication between clients.

Add basic kicker support

---

src/config.ts
src/server.ts

This saves having to manually set up the IMAGE_SALT env var locally before running.
Note, we still look for the var but then fallback to fetching from parameter store. The env var is preferred as it will be quicker in the lambda.

Dynamically fetch image salt

---

src/components/Card.tsx
src/image.test.ts
src/image.ts

Seems to reduce the resultant filesize by 2/3rds or so which is kinder to users and also a better UX/will help avoid users seeing alt-text while the image loads.

Reduce image size on small cards

---

src/components/Footer.tsx

As we require it even though the attribute is deprecated in modern browsers.
Means we no longer need to use `--no-verify` when we push! :)

Disable type error on bgcolor

---

src/components/Card.tsx

Removing border around the quote image on Lotus Notes 8.5 and Outlook 2003.

Removing border around the quote image 

---

package.json
src/Email.tsx
src/components/Card.tsx
src/components/Heading.tsx
src/components/Multiline.tsx
src/layout/Grid.tsx
src/styles/fonts.ts
src/styles/responsive-styles.ts
src/third-party.d.ts
yarn.lock

The aim is to separate out the global CSS to make it easier to maintain and also updates fonts to the newest versions.
In a later PR I hope to verify all of the CSS is needed and also rework the font declarations to use the newest font versions.
Note, we don't get editor support for the css unfortunately, but it is still an improvement over the status quo. I did look into importing CSS files directly in Typescript, but it seems difficult without using Webpack or equivalent, which doesn't really seem justified.

Split global CSS out for readability + update fonts

---

src/api.ts
src/components/cards/DefaultCard.tsx

The headline and the quoted icon appearance matched with the original film-today email.
To apply correct headline, I have pointed the headline to "content.header.headline" instead of "content.properties.webTitle". Additionally, in order to make quoted icon visible, I have pointed this to "content.display.showQuotedHeadline" instead of "content.header.isComment", and this now works correctly.

Headline and the quoted icon appearance matched

---

src/components/Collection.tsx
src/layout/Grid.tsx

To handle 7 items (not 8) for the film collection and also fail (kind of) gracefully with the grid when there is an odd number of items.

Use single large card for default and fail grid gracefully

---

src/api.ts
src/components/cards/CommentCard.tsx
src/layout/Grid.tsx

To remove vertical padding/empty space from the table if no contributor images in smaller comment cards (displayed within the grid).

Remove contributor inage table if no images and fix padding

---

bin/upload.sh
src/Email.tsx
src/components/Banner.tsx
src/components/Collection.tsx
src/components/Collections.tsx
src/components/cards/Card.tsx
src/components/cards/LinkCard.tsx
src/components/tests/commentB/Card.tsx
src/components/tests/commentB/Collection.tsx
src/components/tests/commentB/Grid.tsx
src/components/tests/commentC/Card.tsx
src/components/tests/commentC/Collection.tsx
src/components/tests/commentC/Grid.tsx
src/css.ts
src/layout/Grid.tsx
src/layout/Padding.tsx
src/server.ts

We've implemented this:
and also fixed some markup issues.
There are still a couple of TODOs:
* arrow image location
* hide jobs section
* colour of editorial collection

Opinion 'C' variant

---

src/components/tests/commentB/Card.tsx
src/components/tests/commentB/Grid.tsx
src/components/tests/commentC/Card.tsx
src/components/tests/commentC/Grid.tsx

This fixes an issue on some email clients where there's an unwanted white space between the author cutout and the edge of the cell it sits in.
Same change on both variants of Opinion (in Grid and Card itself).

Setting padding 0 on Opinion grid/card with author cutout

---

src/styles/fonts.ts

* increase range of fonts loaded so we don't try and use fonts we don't include
* fix font smoothing on webkit
(subtle on my high-res macbook pro but the second is sharper. The difference is much more pronounced on lower-res monitors/ones with larger pixels.)

Font fixes

---

src/components/Collections.tsx

Tweaks the condition used to hide the 'Jobs' collection in Opinion so it uses something reasonably reliable other than `displayName`, which will change often during the Black Friday/Cyber Monday period.
Because the editors changed the display name for this collection so the existing condition was no longer able to pick it up, causing it to be rendered (unwanted behaviour) with a design we didn't expect (double unwanted).
https://trello.com/c/tiYGdgee/67-resolve-design-issue-with-guardian-masterclasses-in-opinion-vars-b-c

Ignores Jobs/Masterclasses collection in Opinion emails

---

src/components/cards/OverlayCard.tsx

It adds a new white quote icon.
To support the new Media Briefing design.
https://trello.com/c/UBQJPTSV/77-add-the-white-quote-to-support-media-briefing-c-design
Before:
After:

White quote icon added in to follow Media Briefing C design

---

bin/upload.sh
src/collections/GenericCollection.tsx
src/components/Collections.tsx
src/fronts/media-briefing/MediaBriefing.tsx
src/fronts/media-briefing/variantD/Collections.tsx
src/fronts/media-briefing/variantD/components/CommentCollection.tsx
src/fronts/media-briefing/variantD/components/LinkCollection.tsx
src/fronts/media-briefing/variantD/components/TopCollection.tsx

Adds a Media Briefing variant D - from a copy of variant B but using the 'GenericCollection' to render a 2 x 2 grid for TV & Radio.
Because we want to trial a 2 x 2 grid on Media Briefing vs the current variant B.
https://trello.com/c/dA42OEi4/81-create-new-variant-of-media-briefing-using-2-x-2-grid-for-film-tv

Adds Media Briefing - variant D

---

src/components/cards/CommentCardB.tsx
src/components/cards/CommentCardC.tsx
src/components/cards/DefaultCard.tsx
src/components/cards/DescriptiveCard.tsx
src/components/cards/MediaCardB.tsx
src/components/cards/MediaCardC.tsx
src/components/cards/OverlayCard.tsx

Switches to using the content headline as alt text for the card image, across all cards.
Because we've discovered that using the image alt text in the API may cause some email clients to break.

Use headline as image alt text across all cards

---

src/components/Banner.tsx
src/components/Image.tsx
src/components/cards/CommentCardB.tsx
src/components/cards/CommentCardC.tsx
src/components/cards/DefaultCard.tsx
src/components/cards/DescriptiveCard.tsx
src/components/cards/MediaCardB.tsx
src/components/cards/MediaCardC.tsx
src/components/cards/OverlayCard.tsx

Adds a reusable Image component to be used for all content images. Also replaces all local HTML image tags with an instance of this new component, and cleans lots of old image CSS.
So that we can easily reuse image styles across the cards.
https://trello.com/c/RnfHDPUN/85-create-image-component

Adds Image component & cleans lots of CSS

---

src/components/cards/DefaultCard.tsx
src/fronts/film-today/variantB/Collections.tsx
src/fronts/film-today/variantB/components/DefaultCollection.tsx
src/fronts/film-today/variantC/components/DefaultCollection.tsx
src/fronts/media-briefing/variantD/Collections.tsx
src/fronts/opinion/variantB/components/Grid.tsx
src/fronts/opinion/variantC/components/Grid.tsx
src/layout/Grid.tsx

Reverts Film Today variant B to use the previous design based on two lead stories plus a grid of 2 x 2.
Because this designs works better than the one we were trying out.
https://trello.com/c/K8F08mFg/87-revert-previous-design-on-film-today-variant-b

Reverts Film Today variant B to original design

---

src/components/Image.tsx
src/components/cards/CommentCardB.tsx
src/components/cards/CommentCardC.tsx

Extends the Image component so that a prop can be passed in telling it to not add the default 'width' property. Currently only useful in Opinion (contributor images).
Because a default `width: 100%` on Contributor images was causing issues on some email clients.

Image accepts prop to bypass default width

---

src/cdk/app.ts
src/server.ts

Adds a basic healthcheck.
Note, once I'm confident this is working okay, I'll create a separate PR to add the actual alarm on this.
To let us know if the service goes down for some reason.
https://trello.com/c/taC5yjWL/79-production-ready-tasks

Add Route53 healthcheck

---

src/components/cards/DefaultCard.tsx
src/fronts/opinion/variantB/Collections.tsx
src/fronts/opinion/variantC/Collections.tsx
src/fronts/sport-au/variantC/components/DefaultCollection.tsx
src/fronts/sport-au/variantC/components/TopCollection.tsx
src/layout/Grid.tsx

Extends the DefaultCard so it knows whether or not it's being used inside a Grid, and therefore conditionally apply border and/or background which may otherwise be responsibility of the grid cell. Also expands the Grid component so it can take those same two styles and use them properly if they're responsibility of the Grid and not the Card. 😒
NOTE: the previous implementation worked fine on 99.99% of the cases; only a tiny minority of email clients had an issue with it; but we decided to fix the issue anyway so that we're confident we have the same behaviour across clients.
Because we can't rely on Cards expanding vertically to take the height available in the cell, due to email client inconsistencies. Therefore, we need to programatically define whether the Card or the Grid cell should …

Conditionally apply background/border to DefaultCard or Grid cell

---

src/Email.tsx
src/Text.tsx
src/components/Footer.tsx

Adds disclaimer/address to text-only version.
For parity.
https://trello.com/c/yK4zgCuI/99-add-disclaimer-to-text-only-version

Add disclaimer to text version

---

README.md
src/cdk/app.ts
src/server.ts

* ensure we log server errors to Cloudwatch (very basic atm)
* document troubleshooting
* add retention period for logs to ensure we don't keep them forever(!)
Production readiness.
https://trello.com/c/taC5yjWL/79-production-ready-tasks

Logging improvements

---

src/components/cards/CommentCardB.tsx
src/components/cards/CommentCardC.tsx
src/fronts/opinion/variantB/components/Grid.tsx
src/fronts/opinion/variantC/components/Grid.tsx

🚨We should merge and deploy this fix before the 5pm Opinion email today 🚨
Adds checks around the `getContributor()` function call in Opinion so we can handle the case where contributor is `undefined`.
Because we assumed that a 'Contributor' tag would exist in every Opinion story - but now we've found that's not true. This fix stops an error being thrown in that scenario.

Bugfix - adds checks around getContributor

---

riff-raff.yaml
src/cdk/app.ts

This ensures the lambda actually reloads/receives the updated code.
So deploys actually work/update things.
Previously, we updated the cloudformation and s3 zip file, but this is not enough to refresh the lambda as it needs to be prodded to reload the code.
https://trello.com/c/taC5yjWL/79-production-ready-tasks

Use aws-lambda deploy type

---

src/Email.tsx
src/components/Banner.tsx
src/components/Footer.tsx
src/components/QuotationMark.tsx
src/utils/pillarProps.ts

Uses new image locations.
Files live under:
https://static.guim.co.uk/editorial-emails/*
e.g.
https://static.guim.co.uk/editorial-emails/big-numbers/1.png
So that any images in use are stored in the same s3 bucket and easy to manage/won't get accidentally deleted or changed.
https://trello.com/c/odqFLRxl/105-update-image-locations

Migrate images

---

src/components/cards/MostViewedCard.tsx

The URI used by the 'index images' in MostViewedCard to use the static link.
Because we should use the static link.

Tweak index image URL to use static link

---

src/collections/MostViewedCollection.tsx
src/components/cards/DefaultCard.tsx
src/fronts/business-today/variantB/components/DefaultCollection.tsx

Adds tweaks to DefaultCollection to render headlines as per designs.
So we can render headlines on Business Today using existing components.

Business Today - Headlines collection

---

src/components/FreeTextLink.tsx
src/components/TextLink.tsx
src/components/cards/FreeTextCard.tsx
src/utils/getTransformedFreeText.tsx

Adds support for images inside a Free Text container.
Editors can't currently add images, but we should ensure our app doesn't break if ones comes through in the free text. 🤷‍♂️

Free Text Images

---

src/fronts/film-today/variantZ/Collections.tsx

Adds support for the Most Viewed collection in Film Today Variant Z.
Because we recently added this container to the email but never did any work to support it on this variant that we're no longer using.
Because we'd rather not have any broken variants in the app if we can fix them easily.

Adds support for Most Viewed in Film Today Z (archived)

---

src/cdk/app.ts

This adds the creation of (almost) all the necessary components to put an API gateway behind a custom domain name. I suspect these configurations had been done manually in the previous incarnations of the project as I don't recall CDK supporting all these constructs last year.
Missing from that CDK template is the actual CNAME DNS record creation, which can't be automated as it is created outside of AWS' remit, and requires a message to our DNS team.
This allows for an easier creation of a new environment, or re-deploying the app if we were to delete the stack again.
n/a

(almost) Create the Domain name with the CDK stack

---

docs/01-getting-started.md

Updating the documentation with any information I think would be useful
The project will probably paused for at least another quarter, it needs to be easy to be picked up
N/A

Update the documentation with the work done in Q3
